apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: sampleapp
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
